# development_user = "laudosdbdba"
# development_pass = "amk?CULsKW%KZpAo"
development_user = "postgres"
development_pass = "1234"
development_db = "localhost:5432/laudosdb?client_encoding=utf8"
production_user = "laudosdbusr"
production_pass = "Nzr7]vUJBa3k"
production_db = "leo.solvencia.local:5432/laudosdb?client_encoding=utf8"